$env:JAVA_HOME = "C:\Program Files\Eclipse Adoptium\jdk-25.0.2.10-hotspot"
$env:DATABASE_URL = "jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require"
$env:DATABASE_USERNAME = "postgres.qovfwuzqworqmrubgxjf"
$env:DATABASE_PASSWORD = "Bustech2026"
$env:JWT_SECRET = "dev-secret-key-must-be-replaced-in-production-256bits"
$env:JWT_EXPIRATION_MS = "86400000"
$env:CONTAAZUL_CLIENT_ID = "4evlkglsk3011p2buj1ggq107r"
$env:CONTAAZUL_CLIENT_SECRET = "11qqiuc052cu18i59v4vlp04j83ilbnil0lu90aukgi5jqrkk6dq"
$env:CONTAAZUL_REDIRECT_URI = "https://contaazul.com"
$env:SERVER_PORT = "8081"
$env:SPRING_PROFILES_ACTIVE = "dev"

Write-Host "Iniciando CRM-ERP Backend na porta 8081..."
mvn spring-boot:run "-Dspring-boot.run.jvmArguments=-Djava.net.preferIPv6Addresses=true"
